//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryViewModel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockDetail
    {
        public int Id { get; set; }
        public Nullable<int> SalesId { get; set; }
        public Nullable<int> SalesReturnId { get; set; }
        public Nullable<int> PurcheaseId { get; set; }
        public Nullable<int> PurcheaseReturnId { get; set; }
        public Nullable<int> StockId { get; set; }
        public Nullable<decimal> StockReplace { get; set; }
        public Nullable<decimal> TransReplace { get; set; }
        public Nullable<decimal> TotalReplace { get; set; }
        public Nullable<decimal> StockReturn { get; set; }
        public Nullable<decimal> TransReturn { get; set; }
        public Nullable<decimal> TotalReturn { get; set; }
        public Nullable<decimal> StockDiscount { get; set; }
        public Nullable<decimal> TransDiscount { get; set; }
        public Nullable<decimal> TotalDiscount { get; set; }
        public Nullable<decimal> TransSlup { get; set; }
        public Nullable<decimal> StockSlup { get; set; }
        public Nullable<decimal> TotalSlup { get; set; }
        public Nullable<decimal> StockQuantity { get; set; }
        public Nullable<decimal> TransQuantity { get; set; }
        public Nullable<decimal> TotalQuantity { get; set; }
        public Nullable<decimal> TotalPaid { get; set; }
        public Nullable<decimal> StockPrice { get; set; }
        public Nullable<decimal> TransPrice { get; set; }
        public Nullable<decimal> TotalPrice { get; set; }
        public string Remarks { get; set; }
        public Nullable<bool> StockStutes { get; set; }
        public string Date { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsArchive { get; set; }
        public string CreatedBy { get; set; }
        public string CreatedAt { get; set; }
        public string CreatedFrom { get; set; }
        public string LastUpdateBy { get; set; }
        public string LastUpdateAt { get; set; }
        public string LastUpdateFrom { get; set; }
    }
}
